### ISSUE TITLE
Increase files size limits to 60Mo

### ISSUE THREAD

**Issue by leokante** [OpenSourcePolitics/decidim#233]
**Is your feature request related to a problem? Please describe.**
A client from MEL absolutely needs to upload heavy files in their consultations - files that can be from 30Mo to100Mo. 
I haven't succeeded to compress the document enough (i tried with Adobe) to fit under the 10Mo limit. 

As a user I want to upload heavy files in order to be compliant with the law regarding public consultation.
 
**Describe the solution you'd like**
As a user, I want to upload heavy files. Is it possible to increase the files size limit on attachment?

**Describe alternatives you've considered**
I haven't succeeded to compress the document enough (i tried with Adobe) to fit under the 10Mo limit. 

**Additional context**
Those files aren't created by the client. usually it comes from their private partners. They can not really deal with the issue of the size of thoses files. 

**Does this issue could impact on users private data?**
No.

**Comment by virgile-dev** [comment]
Looking forward to have @moustachu 's perspective on this. They suggested that they could have files that could weight several gigas. We need to find some kind of middle ground here and understand the implication for the server.

**Comment by armandfardeau** [comment]
this is a typical case of high latency / large request. In carrierwave files, uploads are typically loaded in memory. Furthermore, we don't have a loader on the client side so this could be really costly to develop. I would recommend having a look at external services, AWS S3 or FTP for this usage.

**Comment by moustachu** [comment]
Please notes that we need to consider 2 domain for this issue : 

Application : 
- UX : there is no progress bar for upload 
- Permissions : large files should only be permit for admins 
- Performance : we need to check that large files will not slow down request processing for other users

Hosting / Server : 
- Need to have enough disk space to host these files 
- Need to also expand the backup ressource
- We also need to check that large files will not slow down request processing for other users

Given all these issues, I agree to : 
- increase the attachment file size to 250 Mb
- make sure it's only accessible to process administrator
- add the possibility to add an attachment as an external URL (aside the legacy upload button)

**Comment by virgile-dev** [comment]
So to sum up, action map 

## Phase 1
- [ ] increase the attachment file size to 200 Mb
- [ ] make sure it's only accessible to process administrator on this specific task of linking a document

## Phase 2
- [ ] add the possibility to add an attachment as an external URL (aside the legacy upload button)
// Will link meta decidim proposal in here.

**Comment by moustachu** [comment]
⚠️ Proposal attachment are not concerned by this enhancement because the validations involved are shared with the user side

**Comment by armandfardeau** [comment]
@moustachu That seems better for now. The need was only on PP attachments.
