### ISSUE TITLE
Participatory Budget V1

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#419]
## Description
BP needs improvement

## User Stories / Bug fixes
- [x]  Enhanced UX for vote confirmation - #343
- [x]  Email notification for vote confirmation - #337 
- [x]  Export all data - #444
- [ ]  Proposals search BO - #454 
- [x]  Budget instructions - #455
- [ ]  Proposals filters BO - #456

**Comment by moustachu** [comment]
> _an epic is already at level ♾️._
