### ISSUE TITLE
Instances to update/boot

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#428]
## Instances to update/boot
- [x] Villeurbanne - 0.12 - #420, #424 
- [x] Angers - 0.12 - bump must include #289, #348, #459 & #458 
- [x] CD44 - 0.12 - bump must include #348 & fix for #457
- [x] MEL - 0.12 - bump must include #348 
- [x] Nanterre - 0.12 - bump must include #348
- [x] Saint-Jean de Braye - 0.12 - bump must include #348
- [x] Nancy - 0.12 - bump must include #348
- [x] New OSP - 0.16 - boot for internal purposes
