### ISSUE TITLE
Preferential voting

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#495]
## Description
The objective is to introduce preferential voting into Decidim. One solution could be to re-use the vote per project feature from the budget component. The other would be to modify the "sorting" question behaviour in a survey. The objective is to assess the cost to develop for each solution.

## User Stories
**Vote per project revamp**
- [ ]  Rank selected then voted projects - #494
- [ ]  Build serializer for projects in budget component - #496

Or

**Sorting question tweak**
- [ ]  Incomplete sorting question - #493

**Objective is to estimate how long this different user stories would take**

**Comment by lu-hamani** [comment]
Client has put the project on hold. I close the epic but keep the issues opened as we can expect similar requests soon.
