### ISSUE TITLE
Merge, Updates & BCN

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#510]
## Merges
**0.16**
- [x]  - Fix display of comments count when comment has been moderated - #349
- [x]  - Fix stats display - #356
- [x]  - Feature/hide comments on cards when blocked - #357 
- [x]  - Feature/cards hover effect - #436 
- [x]  - Fix empty action btn text - #491  
- [x]  - Crowdin translations - #511 

## BCN
**Send**
- [x] - Fix display of comments count when comment has been moderated - #349  
- [x] - Fix stats display - #356
- [x] - Feature/hide comments on cards when blocked - #357 

**Pull**
- [x] - Don't let users vote/follow withdrawn proposals - https://github.com/decidim/decidim/pull/4909

## Updates
- [x] - dev.steamroll.osp.cat => all of the PR/Issues mentioned above
- [x] - http://club.decidim.opensourcepolitics.eu => to 0.16
- [x] - Angers => #432 = https://github.com/OpenSourcePolitics/decidim/commit/9791bfb8049e091f19602b045156559da060212c
