### ISSUE TITLE
Boot, Merge, Update

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#516]
## Merges
- [x] - Hashtags #532 
- [x] - Conversation message error #512 
- [x] - Popup Map preview #524 
- [x] - Step CTA fix #488 
 
**Merge if dealt with** 
- [x] - Budget jar stripes #472  
- [x] - Notification content #482  
- [x] - BO background highlight #508 
- [x] - Dropdown process navbar #474  

## Boot & Updates
- [x] - Generation.s (0.16)
- [x] - Entrouvert (0.16)
- [x] - NEC (0.16)
- [x] - Club utilisateurs (0.16)
- [x] - bp.osp.cat (0.16) with #337 , #513 , #343 , #455 if all are done.

**Comment by moustachu** [comment]
![out](https://user-images.githubusercontent.com/464350/54369634-8e5c2700-4676-11e9-82b5-3d45895a3efd.gif)

### _Popup Map preview for Proposals 🎉_
