### ISSUE TITLE
Pull, Merge, Update, Boot 

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#566]
## OSP
**Merge**
- [x] - reply comments blocked => #553 
- [x] - word-break => #550
 
**Boot & Updates**
- [x] - CD44 (0.12) => include fix for #457 
 
## BCN
**Backport**
- [x] - Reply to comments => decidim#4938

**Send**
