### ISSUE TITLE
Various platform config change

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#574]
**Tasks**
- [x] - Client doesn't want to track its users. Only technical cookies are required. Cookies consent must be removed.
- [x] - Mailjet rewrite the links. It is an unwanted user tracking. Links should be directly the platform URL. Links are only rewritten on the HTML part.
- [x] - https is not included within the email sent. It should be https instead of http
