### ISSUE TITLE
Proposals export

### ISSUE THREAD

**Issue by armandfardeau** [OpenSourcePolitics/decidim#601]
- [ ] https://github.com/OpenSourcePolitics/decidim/issues/479 Exporting proposals and collaborative drafts
- [ ] https://github.com/OpenSourcePolitics/decidim/issues/480 Exporting proposals sub-categories
- [ ] https://github.com/OpenSourcePolitics/decidim/issues/507 Exporting proposals attachments
- [ ] https://github.com/OpenSourcePolitics/decidim/issues/442 Exporting proposals authors
- [ ] https://github.com/OpenSourcePolitics/decidim/issues/441 Exporting proposals status
- [ ] https://github.com/OpenSourcePolitics/decidim/issues/478 Exporting proposals followers
- [ ] https://github.com/OpenSourcePolitics/decidim/issues/481 Exporting proposals & amendments
