### ISSUE TITLE
SASS - Analytics and Business intelligence

### ISSUE THREAD

**Issue by armandfardeau** [OpenSourcePolitics/decidim#735]
## User Stories
- [ ]  -# As a system, I want to display data insights in order to understand and improve user experience.
- [ ]  -# As a system, I want to record activity from users in order to track activity.
- [ ]  -# As an admin, I want to manage my matomo activity in order to track activity.

**Comment by armandfardeau** [comment]
Idea: https://github.com/ankane/blazer
